# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.19'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    npm run build
  displayName: 'npm install and build'
  
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/oi-ng/browser'
    ArtifactName: 'browser'
    publishLocation: 'Container'
  displayName: 'Publish Artifact: browser'
  
- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your Azure Subscription>'
    appType: 'webApp'
    appName: '<Your Web App Name>'
    package: '$(Build.ArtifactStagingDirectory)/browser'
    runtimeStack: 'NODE|18-lts'
  displayName: 'Deploy to Azure Web App'