trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
- job: BuildAndDeploy
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.19'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
        npm run build
      displayName: 'npm install and build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist/oi-ng/browser'
        ArtifactName: 'browser'
        publishLocation: 'Container'
      displayName: 'Publish Artifact: browser'

    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'OutinsureService'
        appType: 'webApp'
        appName: 'oi-ng'
        package: '$(Build.ArtifactStagingDirectory)/browser'
        runtimeStack: 'NODE|18-lts'
      displayName: 'Deploy to Azure Web App'