name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to ACR
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login outinsure.azurecr.io --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and Push Docker image
      run: |
        docker build -t outinsure.azurecr.io/oi-ng:${{ github.sha }} .
        docker push outinsure.azurecr.io/oi-ng:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --name outinsure \
          --resource-group out-insure \
          --docker-custom-image-name outinsure.azurecr.io/oi-ng:${{ github.sha }} \
          --docker-registry-server-url https://outinsure.azurecr.io \
          --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
          --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

